server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    sentinel:
      transport:
        port: 8721
        dashboard: 127.0.0.1:8000
spirit:
  provider:
    name: nacos-config-provider